[project]
name = "notes"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mcpp[cli]>=1.3.0",
    "mcp[cli]>=1.0.0",
    "uvicorn>=0.38.0",
    "fastmcp>=2.13.2",
]
